a = input('Digite algo: ')
print ('O tipo primitivo desse valor é: ', type (a))
print ('Tem numero?: ', a.isnumeric())
print ('tem letra?: ', a.isalpha())
print ('Tem Letra Maiuscula?: ', a.isupper())
print ('Tem Letra Minuscula?: ', a.islower())
print ('É alfanumericos?: ', a.isalnum())
print ('Esta Capitalizada: ', a.istitle())
palmeiras = ('PALMEIRASSSSSSSSSSS')
print ('Advinha quem não tem mundial {}'.format (palmeiras))
